export const envVariableKeys = {
  env: 'ENV',
  dbType: 'DB_TYPE',
  dbHost: 'DB_HOST',
  dbPort: 'DB_PORT',
  dbUsername: 'DB_USERNAME',
  dbPassword: 'DB_PASSWORD',
  dbDatabase: 'DB_DATABASE',
  googleClientId: 'GOOGLE_CLIENT_ID',
  googleClientSecret: 'GOOGLE_CLIENT_SECRET',
  googleCallbackUrl: 'GOOGLE_CALLBACK_URL',
  accessTokenSecret: 'ACCESS_TOKEN_SECRET',
  refreshTokenSecret: 'REFRESH_TOKEN_SECRET',
  frontLoginRedirectUrl: 'FRONT_LOGIN_REDIRECT_URL',
  awsSecretAccessKey: 'AWS_SECRET_ACCESS_KEY',
  awsAccessKey: 'AKIAY2LKRQET7E4FLDCM',
  awsRegion: 'AWS_REGION',
  bucketName: 'BUCKET_NAME',
  kakaoRestApiKey: 'KAKAO_REST_API_KEY',
  kakaoBookApiUrl: 'KAKAO_BOOK_API_URL',
};
