export const envVariableKeys = {
  env: 'ENV',
  databaseUrl: 'DATABASE_URL',
  assetBaseUrl: 'ASSET_BASE_URL',
  googleClientId: 'GOOGLE_CLIENT_ID',
  googleClientSecret: 'GOOGLE_CLIENT_SECRET',
  googleCallbackUrl: 'GOOGLE_CALLBACK_URL',
  kakaoAuthClientId: 'KAKAO_AUTH_CLIENT_ID',
  kakaoAuthClientSecret: 'KAKAO_AUTH_CLIENT_SECRET',
  kakaoAuthCallbackUrl: 'KAKAO_AUTH_CALLBACK_URL',
  accessTokenSecret: 'ACCESS_TOKEN_SECRET',
  refreshTokenSecret: 'REFRESH_TOKEN_SECRET',
  frontLoginRedirectUrl: 'FRONT_LOGIN_REDIRECT_URL',
  awsSecretAccessKey: 'AWS_SECRET_ACCESS_KEY',
  awsAccessKey: 'AWS_ACCESS_KEY_ID',
  awsRegion: 'AWS_REGION',
  bucketName: 'BUCKET_NAME',
  kakaoRestApiKey: 'KAKAO_REST_API_KEY',
  kakaoBookApiUrl: 'KAKAO_BOOK_API_URL',
};
